language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_mailer/ framework/app/libraries/li3_mailer
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../.. && git submodule add https://github.com/swiftmailer/swiftmailer.git libraries/swiftmailer
  - cd app/libraries && git clone git://github.com/UnionOfRAD/li3_quality.git
  - cd ..
  - sed '$d' config/bootstrap/libraries.php > config/bootstrap/testlibraries.php
  - echo "Libraries::add('li3_mailer');" >> config/bootstrap/testlibraries.php
  - echo "Libraries::add('li3_quality');" >> config/bootstrap/testlibraries.php
  - echo "Libraries::add('swiftmailer', array('prefix' => 'Swift_', 'bootstrap' => 'lib/swift_required.php'));" >> config/bootstrap/testlibraries.php
  - echo -n "?>" >> config/bootstrap/testlibraries.php
  - mv config/bootstrap/testlibraries.php config/bootstrap/libraries.php

script: ../libraries/lithium/console/li3 test libraries/li3_mailer/tests && ../libraries/lithium/console/li3 quality syntax --library=li3_mailer
